# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf5d83c618ad6b6e24ac3df039980fa4b0158fa714cc7175ff2eed083e7bc12278d160fb124f329e976640541c12f59e65d16afbc3dacc02c6213c4525a5924

test:
  secret_key_base: 0e5a378c481e76c0495b9d1d4f2de6199868271e2d5ddb3b80f27bdaedcea85a0c7cdac1380cd6f26257bdaded8972583852351d149462962089a13dcb2008c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
